In [9]:
print("Phishing Detection project started!")

Phishing Detection project started!

In [10]:
import pandas as pd
df = pd.read_csv("PhiUSIIL_Phishing_URL_Dataset.csv")
df.head()

,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,...,0.0,0.0,1.0,34.0,20.0,28.0,119.0,0.0,124.0,1.0
1,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,...,0.0,0.0,1.0,50.0,9.0,8.0,39.0,0.0,217.0,1.0
2,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,...,0.0,0.0,1.0,10.0,2.0,7.0,42.0,2.0,5.0,1.0
3,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,...,1.0,1.0,1.0,3.0,27.0,15.0,22.0,1.0,31.0,1.0
4,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,...,1.0,0.0,1.0,244.0,15.0,34.0,72.0,1.0,85.0,1.0

In [11]:
df.shape

(32826, 55)

In [12]:
df["label"].value_counts()

label
1.0    19487
0.0    13338
Name: count, dtype: int64

In [13]:
df.columns

Index(['URL', 'URLLength', 'Domain', 'DomainLength', 'IsDomainIP', 'TLD',
       'URLSimilarityIndex', 'CharContinuationRate', 'TLDLegitimateProb',
       'URLCharProb', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation',
       'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL',
       'LetterRatioInURL', 'NoOfDegitsInURL', 'DegitRatioInURL',
       'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL',
       'NoOfOtherSpecialCharsInURL', 'SpacialCharRatioInURL', 'IsHTTPS',
       'LineOfCode', 'LargestLineLength', 'HasTitle', 'Title',
       'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon', 'Robots',
       'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect', 'HasDescription',
       'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit', 'HasSocialNet',
       'HasSubmitButton', 'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay',
       'Crypto', 'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS',
       'NoOfSelfRef', 'NoOfEmptyRef', 'NoOfExternalRef', 'label'],
      dtype='object')

In [14]:
df.isnull().sum().sum()

np.int64(28)

In [15]:
df[["URL", "label"]].head(10)

                                  URL  label
0    https://www.southbankmosaics.com    1.0
1            https://www.uni-mainz.de    1.0
2      https://www.voicefmradio.co.uk    1.0
3         https://www.sfnmjournal.com    1.0
4  https://www.rewildingargentina.org    1.0
5     https://www.globalreporting.org    1.0
6          https://www.saffronart.com    1.0
7          https://www.nerdscandy.com    1.0
8      https://www.hyderabadonline.in    1.0
9                 https://www.aap.org    1.0

In [16]:
df[df["label"] == 0][["URL", "label"]].head(10)

                                                  URL  label
11                            http://www.teramill.com    0.0
20                        http://www.f0519141.xsph.ru    0.0
21                           http://www.shprakserf.gq    0.0
27             https://service-mitld.firebaseapp.com/    0.0
28                  http://www.kuradox92.lima-city.de    0.0
29                        https://liuy-9a930.web.app/    0.0
31  https://ipfs.io/ipfs/qmrvvyr84esa2assw9vvwupqj...    0.0
32           http://att-103731-107123.weeblysite.com/    0.0
34                https://hidok4f8zl.firebaseapp.com/    0.0
37                               http://www.ooguy.com    0.0

In [21]:
import pandas as pd

df = pd.read_csv("PhiUSIIL_Phishing_URL_Dataset.csv")
print("Rows aur columns:", df.shape)

df = df.dropna(subset=["label"])

X = df.drop(columns=["URL", "Domain", "TLD", "Title", "label"])
y = df["label"]

print("Rows ab:", len(df))
print("X shape:", X.shape)
print("X mein khali values:", X.isnull().sum().sum())

Rows aur columns: (235795, 55)
Rows ab: 235795
X shape: (235795, 50)
X mein khali values: 0

In [22]:
from sklearn.model_selection import train_test_split

print(y.value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(X_train.shape, X_test.shape)

label
1    134850
0    100945
Name: count, dtype: int64
(188636, 50) (47159, 50)

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 score :", f1_score(y_test, y_pred))

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 score : 1.0

In [24]:
from sklearn.metrics import confusion_matrix
import pandas as pd

print(confusion_matrix(y_test, y_pred))

imp = pd.Series(model.feature_importances_, index=X.columns)
print(imp.sort_values(ascending=False).head(10))

[[20189     0]
 [    0 26970]]
URLSimilarityIndex    0.181075
NoOfExternalRef       0.169265
LineOfCode            0.146585
NoOfSelfRef           0.108536
NoOfImage             0.084350
NoOfJS                0.072904
NoOfCSS               0.031598
HasSocialNet          0.031526
HasCopyrightInfo      0.025522
IsHTTPS               0.022940
dtype: float64

In [26]:
url_features = [
    "URLLength", "DomainLength", "IsDomainIP", "TLDLength", "NoOfSubDomain",
    "HasObfuscation", "NoOfObfuscatedChar", "ObfuscationRatio",
    "NoOfLettersInURL", "LetterRatioInURL", "NoOfDegitsInURL", "DegitRatioInURL",
    "NoOfEqualsInURL", "NoOfQMarkInURL", "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL", "SpacialCharRatioInURL", "IsHTTPS",
    "CharContinuationRate", "URLCharProb", "TLDLegitimateProb"
]

model_url = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
model_url.fit(X_train[url_features], y_train)

y_pred_url = model_url.predict(X_test[url_features])

print("Accuracy :", accuracy_score(y_test, y_pred_url))
print("Precision:", precision_score(y_test, y_pred_url))
print("Recall   :", recall_score(y_test, y_pred_url))
print("F1 score :", f1_score(y_test, y_pred_url))
print(confusion_matrix(y_test, y_pred_url))

Accuracy : 0.9966072223753685
Precision: 0.9956370627819271
Recall   : 0.9984427141268075
F1 score : 0.9970379146919431
[[20071   118]
 [   42 26928]]